[tool.poetry]
package-mode = false
name = "romm"
version = "0.0.1"
description = "A beautiful, powerful, self-hosted rom manager"
license = "GNU AGPLv3"
repository = "https://github.com/rommapp/romm"
authors = ["Zurdi <zurdi@romm.app>", "Arcane <arcane@romm.app>"]

[tool.poetry.dependencies]
python = "^3.12"
anyio = "^4.4"
fastapi = "0.110.0"
uvicorn = "0.29.0"
gunicorn = "22.0.0"
websockets = "12.0"
python-socketio = "5.11.1"
SQLAlchemy = "^2.0.30"
alembic = "1.13.1"
PyYAML = "6.0.1"
Unidecode = "1.3.8"
emoji = "2.10.1"
python-dotenv = "1.0.1"
sqlakeyset = "^2.0.1708907391"
pydash = "^7.0.7"
mariadb = "1.1.10"
rq = "^1.16.1"
redis = "^5.0"
types-pyyaml = "^6.0.12.20240311"
types-redis = "^4.6.0.20240311 "
passlib = { extras = ["bcrypt"], version = "^1.7.4" }
itsdangerous = "^2.1.2"
rq-scheduler = "^0.13.1"
starlette-csrf = "^3.0.0"
httpx = "^0.27.0"
python-multipart = "^0.0.9"
types-passlib = "^1.7.7.20240311"
watchdog = "^4.0.0"
yarl = "^1.9.4"
joserfc = "^0.9.0"
pillow = "^10.3.0"
certifi = "2024.07.04"
python-magic = "^0.4.27"
py7zr = "^0.21.1"
streaming-form-data = "^1.16.0"

[tool.poetry.group.test.dependencies]
fakeredis = "^2.21.3"
pytest = "^8.3"
pytest-env = "^1.1.3"
pytest-mock = "^3.12.0"
pytest-asyncio = "^0.23.5"
pytest-recording = "^0.13"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"
mypy = "^1.10.0"
ipykernel = "^6.29.4"
